# Generated by Django 3.0.3 on 2020-02-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
